### ISSUE TITLE
Lies

### ISSUE THREAD

**Issue by SlexAxton** [bendc/jscss#1]
You have to include:
- The time it takes to load and execute jscss.js
- The time it takes to repaint everything since styles are non-blocking
- The flash of unstyled content (for the same reason above)

My suggestion:

Inline jscss.js and any file that's critical for page load rendering should be a blocking script in the head.

Then you don't have to pay any loading penalty for jscss.js (just execution time, which is minimal). And then the styles are injected prior to the body existing, so there's no flash of unstyled content.

**Comment by bendc** [comment]
> - The time it takes to load and execute jscss.js

Aside from the extra HTTP request (that you could avoid by concatenating `jscss.js` and your actual stylesheet), the load and parsing time is negligible.

> - The time it takes to repaint everything since styles are non-blocking
> - The flash of unstyled content (for the same reason above)

As far as I know, there won't be any repaint or FOUC if you insert `jscss.js` and your javascript stylesheet in the `<head>`.
